### ISSUE TITLE
VLAN Test

### ISSUE THREAD

**Issue by bytinbit** [INSRapperswil/nuts#29]
Add Basic TestCase for VLANs via Napalm.
Checks if:

- Do the Switches have the VLANS which they are supposed to have (and nothing else)?
- Trunk: Are only the VLANS allowed which are supposed to be allowed?

**Comment by bytinbit** [comment]
implemented here: https://github.com/marcom4rtinez/nuts/tree/1-test-bundle-prototyp-vlan-test

**Comment by lucmurer** [comment]
Done by @marcom4tinez and @sevigrimm for Release 3.1.0
